## Numpy Array

In [1]:
my_list = [1, 2 ,3 ,4]

In [2]:
import numpy as np
arr = np.array(my_list) # cast the list to numpy array

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
my_matrice = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

In [5]:
np.array(my_matrice)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# generate an array in numpy
np.arange(0,10, 2) # get event number from 0 to 10

array([0, 2, 4, 6, 8])

In [11]:
# generate row and column 
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# generate number between range
np.linspace(0, 5, 10) # from 0 to 5 generate 10 point number

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
# generate identity metrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
# generate random array
np.random.rand(5, 5)

array([[0.73732666, 0.38223306, 0.48464775, 0.83322536, 0.61958923],
       [0.9738974 , 0.5422231 , 0.03912057, 0.89878291, 0.5331867 ],
       [0.38956392, 0.74190475, 0.97060071, 0.31821783, 0.18835297],
       [0.47512511, 0.98892737, 0.66086123, 0.5416679 , 0.89273609],
       [0.09960586, 0.4030447 , 0.82307598, 0.45304181, 0.02679058]])

In [17]:
np.random.randn(2)

array([0.51798576, 0.42780569])

In [23]:
# generate a random number
np.random.randint(1,100)
np.random.randint(1,100,10) # generate 10 random integer

array([10, 75, 89, 65, 78, 76, 96, 11, 55, 60])

In [26]:
# reshape array
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arr2 = np.random.randint(0, 50, 10)

In [29]:
arr2

array([18, 22,  8,  4, 34, 24, 14,  1, 30, 36])

In [30]:
arr.reshape(5, 5) # reshape the array to 5 by 5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
# find the minimum value in the array
arr2.min()

1

In [33]:
# find the max value in the array
arr2.max()

36

In [34]:
# get the index location of max valur
arr2.argmax()

9

In [35]:
# get the index location of min valur
arr2.argmin()

7

In [37]:
# get the shape of the vector
arr.shape

(25,)

In [38]:
# get the datatype fo the array element
arr2.dtype

dtype('int32')

## Numpy Indexing and Selection

In [40]:
arr = np.arange(0, 11)

In [41]:
# get the value using index
arr[8]

8

In [42]:
arr[1:5] # get element starting from 1 to 5

array([1, 2, 3, 4])

In [44]:
arr[:8] # get everything upto position 8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
arr[5:] # start from posiyion 5 and get all the element

array([ 5,  6,  7,  8,  9, 10])

In [46]:
# broadcast value in the array
arr[0:6] = 100

In [47]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [48]:
arr = np.arange(0, 11)

In [49]:
slice_of_arr = arr[:6]

In [50]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [51]:
slice_of_arr[:] = 100

In [52]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [53]:
# if we check our list we might find out tha the slice if the array and our list change
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [54]:
# this shows that numpy doesnot create a copy of the data to avoid memory use of big array but reference the data
# if you want to create a copy make the above syntax
arr_copy = arr.copy()

In [55]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [56]:
arr_copy[:] = 55

In [57]:
# if we check the original array, we gonna notice that we didnt affect the original array
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [58]:
# grab element inside a 2 dimension array
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [59]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d[0][0]# get the element in the fist row and first column (double bracket notation)

5

In [65]:
arr_2d[2,2]# get the element in the second row and second column (single bracket notation)

45

In [66]:
# slice 2 dimension array
arr_2d[:2, 1:] # get everything and not including 0 and 1 as column and dont include 2

array([[10, 15],
       [25, 30]])

In [67]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [78]:
arr_2d[1:, :2]

array([[20, 25],
       [35, 40]])

In [80]:
# condition selection
arr = np.arange(1, 11)

In [81]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
# get the boolean arr
bool_arr = arr > 5

In [83]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [84]:
arr[bool_arr] # return array based on the boolean data in the boolean_arr

array([ 6,  7,  8,  9, 10])

In [85]:
# the easy way to to this is
arr[arr>5] # get all the element that are greater that 5 inside the array

array([ 6,  7,  8,  9, 10])

In [86]:
arr_2d = np.arange(50).reshape(5,10)

In [87]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [97]:
# challenge: select 13, 14, 23, 24
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Numpy Operations

In [98]:
arr = np.arange(0,11)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr + arr # addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [101]:
arr - arr # substration

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [102]:
arr * arr # multiplication

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [103]:
arr + 100 # add 100 to all element inside the arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [104]:
arr/arr

C:\Users\cris_0XC0\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [105]:
np.sqrt(arr) # square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [106]:
np.max(arr) # get the max

10

In [107]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [108]:
np.log(arr)

C:\Users\cris_0XC0\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])